config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  resources :villages, only: [ :create, :show ] do
    member do
      get "resource_selectors" # @todo - change to symbol
      get :resources_stream
    end
    resources :village_buildings, only: [ :create ]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tiles = []
    tile_positions = [
      [ 1, 1 ], [ 1, 2 ], [ 1, 3 ],
      [ 2, 1 ], [ 2, 2 ], [ 2, 3 ], [ 2, 4 ],
      [ 3, 1 ], [ 3, 2 ], [ 3, 3 ], [ 3, 4 ], [ 3, 5 ],
      [ 4, 1 ], [ 4, 2 ], [ 4, 3 ], [ 4, 4 ],
      [ 5, 1 ], [ 5, 2 ], [ 5, 3 ]
    ]

    tile_positions.each do |x, y|
      tile = Tile.find_or_create_by(x: x, y: y)
      @tiles << tile
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_hex_button.html.erb
<div
  data-controller="hex-button"
  class="hex-button"
  data-row="<%= tile.x %>"
  data-col="<%= tile.y %>"
  data-spacer="<%= spacer %>"
  data-tile-id="<%= tile.id %>"
  data-tile-has-village="<%= tile.village.present? %>"
  data-village-link="<%= link %>"
  data-user-has-village="<%= user_has_village %>"
  data-village-owner="<%= tile.village&.user&.username %>"
  data-is-current-user-village="<%= tile.village&.user == current_user %>"
  data-test-target="hex-button-<%= user_has_village ? 'show' : 'create' %>-<%= tile.x %><%= tile.y %>">
</div>

app/views/home/_hex_container.html.erb
<div class="hex-container">
    <% @tiles.each do |tile| %>
      <% user_village = current_user.village %>
      <% if user_village && user_village.tile_id == tile.id %>
        <%= render partial: 'hex_button', locals: { tile: tile, spacer: calculate_spacer(tile), link: village_path(user_village), user_has_village: !user_village.blank? } %>
      <% else %>
        <%= render partial: 'hex_button', locals: { tile: tile, spacer: calculate_spacer(tile), link: nil, user_has_village: !user_village.blank? } %>
      <% end %>
    <% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Villager</title>
</head>
<body>
  <h1>Welcome to Villager</h1>
  <p>This is the homepage of your new Rails application.</p>

  <%= render partial: 'hex_container' %>

  <%= link_to 'home', root_path('test'), method: :post %>
</body>
</html>